<?php

set_time_limit ( 0 );
//$helper = new COM ( 'Helper.clsHelper' ); //helper app for decryption


include_once 'C:/wamp/www/atex/conexao.php';
include_once 'C:/wamp/www/atex/conexao2.php';
include_once 'C:/wamp/www/atex/classes/class.Util.php';

$vetMapearBandeiraCartaoCliente = array ('master' => 'C0038942', 'visa' => 'C0038920', 'amex' => 'C0038936', 'diners' => '109974', 'redecard' => '109973', 'elo' => '109972' );

$vetMapearBandeiraCartaoContaCaixa = array ('master' => 'CCMAST-97', 'visa' => 'CCVISA-92', 'amex' => 'CCAMEX-93', 'diners' => 'CCDIN-9062', 'redecard' => 'CCRDCAR-96', 'elo' => 'CCIELO-99' );

$sql = "SELECT (ROW_NUMBER() OVER(ORDER BY (SELECT MAX(IDLAN) FROM FLAN (NOLOCK)))  + (SELECT MAX(IDLAN) FROM FLAN (NOLOCK))) AS IDLAN";
$rs2 = $db2->Execute ( $sql );
$IDLAN = $rs2->FetchNextObject ()->IDLAN;

$sql = "
SELECT 
	1 AS CODCOLIGADA, 
	$IDLAN AS IDLAN,
	(CASE WHEN p.Id IN (26, 32, 33, 46, 48, 51, 43, 44, 45, 47, 49, 52) THEN pg.ReferenceNumber ELSE substring(o.AdOrderNumber,5,len(o.AdOrderNumber)) END) AS NUMERODOCUMENTO, 
	NULL AS CODIGOBARRA, 
	NULL AS IPTE, 
	NULL AS CNABNOSSONUMERO, 
	0 AS NFOUDUP, 
	0 AS CLASSIFICACAO, 
	1 AS PAGREC, 
	0 AS STATUSLAN, 
	'F' AS CODAPLICACAO, 
	NULL AS CODCOLXCX, 
	NULL AS IDXCX, 
	NULL AS IDFAT, 
	NULL AS IDMOV, 
	NULL AS IDSESSAO, 
	NULL AS IDPGTO, 
	NULL AS CODCCUSTO, 
	o.Notes AS HISTORICO, 
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS DATACRIACAO, 
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS DATAVENCIMENTO,
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS DATAEMISSAO, 
	NULL AS DATABAIXA, 
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS DATAPREVBAIXA,
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS DATACONTABILIZ,
	NULL AS DATACANCELAMENTO, 
	NULL AS DATACANCELBAIXA, 
	NULL AS DATAESTORNOLAN, 
	NULL AS DATACHEQUE, 
	NULL AS DATACONTABILIZBX, 
	NULL AS DATAVENCIMENTOANTECIP, 
	NULL AS DATAOP1, 
	NULL AS DATAOP2, 
	NULL AS DATAOP3, 
	NULL AS DATAOP4, 
	NULL AS DATAOP5, 
	NULL AS DATAPAG, 
	NULL AS MESDECOMPETENCIA, 
	round((CASE WHEN d.Name IS NULL THEN o.NetAmount ELSE (o.NetAmount/CAST(d.Name AS INT)) END),2) AS VALORORIGINAL,
	0 AS VALORBAIXADO, 
	0 AS VALORCAP, 
	0 AS VALORJUROS, 
	0 AS VALORDESCONTO, 
	0 AS VALORCHEQUE, 
	0 AS VALOROP1, 
	0 AS VALOROP2, 
	0 AS VALOROP3, 
	0 AS VALOROP4, 
	0 AS VALOROP5, 
	0 AS VALOROP6, 
	0 AS VALOROP7, 
	0 AS VALOROP8, 
	0 AS VALORMULTA, 
	1 AS VALORAUXILIAR, 
	round((CASE WHEN d.Name IS NULL THEN o.NetAmount ELSE (o.NetAmount/CAST(d.Name AS INT)) END),2) AS VALORBASEIRRF,
	0 AS VALORIRRF, 
	0 AS VALORREPASSE, 
	0 AS VALORVENCIMENTOANTECIP, 
	0 AS VALORNOTACREDITO, 
	0 AS VALORADIANTAMENTO, 
	0 AS VALORDEVOLUCAO, 
	0 AS JUROSDIA, 
	0 AS CAPMENSAL, 
	NULL AS DESCONTOCOMERCIAL, 
	0 AS TAXASVENDOR, 
	0 AS JUROSVENDOR, 
	1 AS CODCOLCFO, 
	(CASE (SELECT u.SalesTeamNameId FROM UsrUsers u (nolock) WHERE u.UserId = o.RepId) WHEN 9 THEN '109983' ELSE (SELECT s.ExternalName FROM ShStringMapper s (nolock) WHERE s.ExternalSystemType = 2 AND s.ObjectType = 9 AND s.AdBaseId = (SELECT u.UserId FROM UsrUsers u (nolock) WHERE u.UserId = o.SellerId)) END) AS CODCFO,
	0 AS CODCOLCXA, 
	NULL AS CODCXA,
	'00007' AS CODTDO, 
	1 AS CODFILIAL, 
	NULL AS CODDEPARTAMENTO, 
	NULL AS NUMEROCHEQUE, 
	(SELECT '@'+CAST(CAST(ROW_NUMBER() OVER(ORDER BY GETDATE())*o.Id AS INT) AS VARCHAR)) AS SERIEDOCUMENTO, 
	NULL AS IDADIANTAMENTO, 
	NULL AS IDNOTACREDITO, 
	NULL AS IDLANREPASSE, 
	NULL AS IDDEVOLUCAO, 
	NULL AS IDBAIXAPARCIAL, 
	NULL AS IDIRRF, 
	NULL AS IDCNT, 
	(CASE (SELECT u.SalesTeamNameId FROM UsrUsers u (nolock) WHERE u.UserId = o.RepId) WHEN 9 THEN '1.04.003' ELSE '1.04.002' END) AS CODTB1FLX,
	(SELECT s.ExternalName FROM ShStringMapper s WHERE s.ExternalSystemType = 2 AND s.ObjectType = 16 AND s.AdBaseId = p.Id) AS CODTB2FLX,
	NULL AS CODTB3FLX, 
	NULL AS CODTB4FLX, 
	NULL AS CODTB5FLX, 
	1 AS TIPOCONTABILLAN, 
	'R$' AS CODMOEVALORORIGINAL, 
	NULL AS CODINDEXADOR, 
	NULL AS FILIALCONTABIL, 
	(CASE WHEN p.Id IN (26, 32, 33, 46, 48, 51, 43, 44, 45, 47, 49, 52) THEN CASE WHEN pg.ReferenceNumber NOT IN ('') THEN pg.ReferenceNumber ELSE substring(o.AdOrderNumber,5,len(o.AdOrderNumber)) END ELSE substring(o.AdOrderNumber,5,len(o.AdOrderNumber)) END) AS NUMEROCONTABIL,
	substring(o.AdOrderNumber,5,len(o.AdOrderNumber)) AS SEGUNDONUMERO, 
	0 AS LIBAUTORIZADA, 
	0 AS STATUSEXPORTACAO, 
	60 AS NUMLOTECONTABIL, 
	0 AS STATUSEXTRATO,
	NULL AS CAMPOALFAOP1, 
	NULL AS CAMPOALFAOP2, 
	UPPER((SELECT (SELECT t.TeamName FROM SalesTeamName t (nolock) WHERE t.SalesTeamId = u.SalesTeamNameId) FROM UsrUsers u (nolock) WHERE u.UserId = o.SellerId)) AS CAMPOALFAOP3, 
	NULL AS CANCELADOFAT, 
	NULL AS FATURADOFAT, 
	NULL AS CNABCARTEIRA, 
	NULL AS CNABCOMANDO, 
	0 AS CNABACEITE, 
	NULL AS CNABINSTRUCAOCOD1, 
	NULL AS CNABINSTRUCAOCOD2, 
	0 AS CNABSTATUS, 
	NULL AS CNABBANCO, 
	0 AS REEMBOLSAVEL, 
	(SELECT CASE WHEN (SELECT s.ExternalName FROM ShStringMapper s (nolock) WHERE s.ExternalSystemType = 2 AND s.ObjectType = 9 AND s.AdBaseId = (SELECT u.UserId FROM UsrUsers u (nolock) WHERE u.UserId = o.RepId)) NOT IN ('', '') THEN (SELECT s.ExternalName FROM ShStringMapper s (nolock) WHERE s.ExternalSystemType = 2 AND s.ObjectType = 9 AND s.AdBaseId = (SELECT u.UserId FROM UsrUsers u (nolock) WHERE u.UserId = o.RepId)) ELSE NULL END) AS CODVEN,
	NULL AS TIPOSAC, 
	NULL AS PERLETIVO, 
	NULL AS PARCELA,
	NULL AS COTA, 
	NULL AS CODBAIXA, 
	NULL AS MENSBAIXA, 
	NULL AS LOCPAG, 
	NULL AS LOTE, 
	NULL AS NUMRECIBO, 
	NULL AS VRDEP, 
	NULL AS SERVEXTRA, 
	NULL AS DTALT, 
	NULL AS HRALT, 
	'mestre' AS USUARIO,
	NULL AS CODRPR, 
	1 AS BAIXAAUTORIZADA, 
	0 AS TEMCHEQUEPARCIAL, 
	0 AS JAIMPRIMIU, 
	NULL AS EMITIDO, 
	0 AS NUMBLOQUEIOS, 
	NULL AS CODUSUDESBLOQUEIO1, 
	NULL AS CODUSUDESBLOQUEIO2, 
	NULL AS NUMCONTABILBX, 
	NULL AS CODEVENTO, 
	NULL AS CODEVENTOBAIXA, 
	NULL AS CHAPA, 
	0 AS COTACAOINCLUSAO, 
	0 AS COTACAOBAIXA, 
	0 AS CARENCIAJUROS, 
	0 AS TIPOJUROSDIA, 
	'mestre' AS USUARIOCRIACAO,
	NULL AS CODRPR, 
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS DATAALTERACAO, 
	0 AS ALTERACAOBLOQUEADA, 
	0 AS MULTADIA, 
	NULL AS IDFORMAPAGTO, 
	NULL AS VALOROPERACAODESCONTO, 
	0 AS DESCONTADO, 
	0 AS VALORINSS, 
	0 AS VALORDEDUCAO, 
	NULL AS NUMLOTECONTABILBX, 
	NULL AS CNABAUTENTICACAO, 
	NULL AS CODDIARIO, 
	NULL AS SEQDIARIO, 
	'F' AS APLICFORMULA, 
	NULL AS FORMULAJUROS, 
	NULL AS FORMULADESCONTO, 
	NULL AS FORMULAMULTA, 
	NULL AS FORMULACAPITALIZACAO, 
	NULL AS FORMULAVALOROP1, 
	NULL AS FORMULAVALOROP2, 
	NULL AS FORMULAVALOROP3, 
	NULL AS FORMULAVALOROP4, 
	NULL AS FORMULAVALOROP5, 
	NULL AS FORMULAVALOROP6, 
	NULL AS FORMULAVALOROP7, 
	NULL AS FORMULAVALOROP8, 
	0 AS INSSEMOUTRAEMPRESA, 
	round((CASE WHEN d.Name IS NULL THEN o.NetAmount ELSE (o.NetAmount/CAST(d.Name AS INT)) END),2) AS PERCENTBASEINSS,
	0 AS OCAUTONOMO, 
	NULL AS CODDIARIOBAIXA, 
	NULL AS SEQDIARIOBAIXA, 
	NULL AS SEQDIARIOESTORNOBAIXA, 
	NULL AS SEQDIARIOESTORNO, 
	NULL AS NSEQITMCNT, 
	NULL AS DATAFATCNT, 
	NULL AS NUMSEQRECIBO, 
	NULL AS DATARECIBO, 
	NULL AS CODRECEITA, 
	NULL AS ALIQUOTA, 
	NULL AS IDGUIA, 
	round((CASE WHEN d.Name IS NULL THEN o.NetAmount ELSE (o.NetAmount/CAST(d.Name AS INT)) END),2) AS PERCBASEINSSEMPREGADO,
	0 AS IMPOSTOEDITADO, 
	0 AS REUTILIZACAO, 
	NULL AS CNABCODRETORNO, 
	NULL AS MOEDAVINCULO, 
	NULL AS IDBOLETO, 
	0 AS CATEGORIAAUTONOMO, 
	0 AS VALORSESTSENAT, 
	NULL AS CONVENIO, 
	NULL AS DIGCONVENIO, 
	NULL AS CODCOLCFOORIGEM, 
	NULL AS CODCFOORIGEM, 
	0 AS VRPERDAFINANCEIRA, 
	0 AS VRBASEINSSOUTRAEMPRESA, 
	NULL AS NSEQITMPREVISAO, 
	round((CASE WHEN d.Name IS NULL THEN o.NetAmount ELSE (o.NetAmount/CAST(d.Name AS INT)) END),2) AS VALORSERVICO,
	0 AS VRBASEINSS, 
	0 AS VRBASEIRRF, 
	0 AS STATUSDDA, 
	0 AS VALORDEDUCAODEPENDENTES, 
	0 AS BAIXAPENDENTE, 
	NULL AS MULTAFIXA, 
	0 AS STATUSAVP, 
	NULL AS IDBORDERO, 
	'mestre' AS RECCREATEDBY,
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS RECCREATEDON, 
	'mestre' AS RECMODIFIEDBY,
	convert(datetime,convert(varchar,o.CreateDate,103),103) AS RECMODIFIEDON, 
	0 AS VALORORIGINALBX, 
	0 AS VALORDESCONTOBX, 
	0 AS VALORJUROSBX, 
	0 AS VALORMULTABX, 
	0 AS VALORCAPBX, 
	0 AS VALOROP1BX, 
	0 AS VALOROP2BX, 
	0 AS VALOROP3BX, 
	0 AS VALOROP4BX, 
	0 AS VALOROP5BX, 
	0 AS VALOROP6BX, 
	0 AS VALOROP7BX, 
	0 AS VALOROP8BX, 
	0 AS VALORINSSBX, 
	0 AS VALORIRRFBX, 
	0 AS VALORSESTSENATBX, 
	0 AS VALORDEVOLUCAOBX, 
	0 AS VALORNOTACREDITOBX, 
	0 AS VALORADIANTAMENTOBX, 
	0 AS VALORJUROSVENDORBX, 
	0 AS VALORRETENCOESBX, 
	0 AS VALORPERDAFINANCEIRABX, 
	0 AS VALORVINCULADO, 
	0 AS MODELOCONTABILIZACAO, 
	0 AS MODELOCONTABILIZACAOBAIXA,
	NULL AS IDOPERACAOBAIXA, 
	0 AS VALORDESCONTODUPLICATA, 
	NULL AS IDLANMOVORIGEM, 
	0 AS VALORDESCONTOACORDO, 
	0 AS VALORJUROSACORDO, 
	0 AS VALORACRESCIMOACORDO,
	(CASE WHEN d.Name IS NULL THEN 1 ELSE d.Name END) AS NUMEROPARCELAS,
	(
	CASE 
		WHEN 
			p.Id IN (32, 43)
		THEN 
			'master'
		ELSE 
			CASE 
				WHEN 
			   		p.Id IN (33, 44)	
				THEN 
					'visa'
				ELSE 
					CASE 
						WHEN 
							p.Id IN (26, 45)
						THEN 
							'amex'
						ELSE 
							CASE 
								
							WHEN 
								p.Id IN (51, 52)
							THEN 
								'diners'
							ELSE 
								CASE 
									WHEN 
								 		p.Id IN (46, 47)	
									THEN 
										'elo'
									ELSE 
										CASE 
											WHEN 
												p.Id IN (48, 49)
											THEN 
												'redecard'
											ELSE 
												NULL
										END
								END
						END
				END
			END
	END
	) AS BANDEIRA,
	(CASE WHEN p.Id IN (43, 44, 45, 47, 49, 52) THEN 'debito' ELSE CASE WHEN p.Id IN (26, 32, 33, 46, 48, 51) THEN 'credito' ELSE CASE WHEN p.Id IN (17, 29, 50) THEN 'dinheiro' ELSE CASE WHEN p.Id IN (35) THEN 'carteira' ELSE CASE WHEN p.Id IN (13) THEN 'nota' ELSE 'outros' END END END END END) AS TIPOPAGAMENTO,
	o.Id AS IDORDEM
FROM AoAdOrder o (nolock)
INNER JOIN UsrUsers u (nolock) ON (o.SellerId = u.UserId)
INNER JOIN AoOrderCustomers oc (nolock) ON (oc.adorderid = o.id and oc.payedby = 1 AND oc.PaymentMethod IN (26, 32, 33, 46, 48, 51, 43, 44, 45, 47, 49, 52, 17, 29, 50, 35))
LEFT JOIN AoPayments pg (nolock) ON (pg.PaymentMethod = oc.PaymentMethod AND oc.AdOrderId = pg.ApplyAdOrderId)
LEFT JOIN AoCreditDebit cd (nolock) ON (cd.Id = pg.TransId)
LEFT JOIN PaymentMethodType p (nolock) ON (p.id = oc.PaymentMethod)
LEFT JOIN CfDivision d (nolock) ON (d.Id = cd.DivisionId)
WHERE
	(convert(datetime,convert(varchar,o.CreateDate,103),103) >= convert(datetime,convert(varchar,getdate() - convert(datetime,5),103),103)) AND
	(convert(datetime,convert(varchar,o.CreateDate,103),103) <= convert(datetime,convert(varchar,getdate(),103),103)) AND
	(o.OrderStatusId = 4) AND
	(o.CurrentQueue = 3) AND
	(p.Id IN (26, 32, 33, 46, 48, 51, 43, 44, 45, 47, 49, 52, 17, 29, 50, 35)) AND
	(u.SalesTeamNameId IN (1, 9, 10, 11, 12, 13, 14, 15, 16, 17, 22, 23)) AND
	(o.CustomPackNumber IS NULL OR o.CustomPackNumber = '') AND
	((SELECT TOP 1 r.RefAdOrder FROM CoFulfillmentRec r (nolock) WHERE r.RefAdOrder = o.Id) IS NULL) AND
	(NOT EXISTS (SELECT * FROM [10.10.15.66].CorporeRM.DBO.FLAN F (NOLOCK) WHERE F.CODCOLIGADA = 1 AND F.PAGREC = 1 AND F.RECCREATEDBY = 'mestre' AND F.SEGUNDONUMERO = substring(o.AdOrderNumber,5,len(o.AdOrderNumber)) COLLATE Latin1_General_CI_AS))
";

$rs = $db->Execute ( $sql );

if ($rs->RecordCount () > 0) {
	
	if ($rs) {
		while ( $o = $rs->FetchNextObject () ) {
			
			$CODCOLIGADA = $o->CODCOLIGADA;
			$NUMERODOCUMENTO = $o->NUMERODOCUMENTO;
			$CODIGOBARRA = $o->CODIGOBARRA;
			$IPTE = $o->IPTE;
			$CNABNOSSONUMERO = $o->CNABNOSSONUMERO;
			$NFOUDUP = $o->NFOUDUP;
			$CLASSIFICACAO = $o->CLASSIFICACAO;
			$PAGREC = $o->PAGREC;
			$STATUSLAN = $o->STATUSLAN;
			$CODAPLICACAO = $o->CODAPLICACAO;
			$CODCOLXCX = $o->CODCOLXCX;
			$IDXCX = $o->IDXCX;
			$IDFAT = $o->IDFAT;
			$IDMOV = $o->IDMOV;
			$IDSESSAO = $o->IDSESSAO;
			$IDPGTO = $o->IDPGTO;
			$CODCCUSTO = $o->CODCCUSTO;
			$HISTORICO = $o->HISTORICO;
			$DATACRIACAO = $o->DATACRIACAO;
			$DATAVENCIMENTO = $o->DATAVENCIMENTO;
			$DATAEMISSAO = $o->DATAEMISSAO;
			$DATABAIXA = $o->DATABAIXA;
			$DATAPREVBAIXA = $o->DATAPREVBAIXA;
			$DATACONTABILIZ = $o->DATACONTABILIZ;
			$DATACANCELAMENTO = $o->DATACANCELAMENTO;
			$DATACANCELBAIXA = $o->DATACANCELBAIXA;
			$DATAESTORNOLAN = $o->DATAESTORNOLAN;
			$DATACHEQUE = $o->DATACHEQUE;
			$DATACONTABILIZBX = $o->DATACONTABILIZBX;
			$DATAVENCIMENTOANTECIP = $o->DATAVENCIMENTOANTECIP;
			$DATAOP1 = $o->DATAOP1;
			$DATAOP2 = $o->DATAOP2;
			$DATAOP3 = $o->DATAOP3;
			$DATAOP4 = $o->DATAOP4;
			$DATAOP5 = $o->DATAOP5;
			$DATAPAG = $o->DATAPAG;
			$MESDECOMPETENCIA = $o->MESDECOMPETENCIA;
			$VALORORIGINAL = $o->VALORORIGINAL;
			$VALORBAIXADO = $o->VALORBAIXADO;
			$VALORCAP = $o->VALORCAP;
			$VALORJUROS = $o->VALORJUROS;
			$VALORDESCONTO = $o->VALORDESCONTO;
			$VALORCHEQUE = $o->VALORCHEQUE;
			$VALOROP1 = $o->VALOROP1;
			$VALOROP2 = $o->VALOROP2;
			$VALOROP3 = $o->VALOROP3;
			$VALOROP4 = $o->VALOROP4;
			$VALOROP5 = $o->VALOROP5;
			$VALOROP6 = $o->VALOROP6;
			$VALOROP7 = $o->VALOROP7;
			$VALOROP8 = $o->VALOROP8;
			$VALORMULTA = $o->VALORMULTA;
			$VALORAUXILIAR = $o->VALORAUXILIAR;
			$VALORBASEIRRF = $o->VALORBASEIRRF;
			$VALORIRRF = $o->VALORIRRF;
			$VALORREPASSE = $o->VALORREPASSE;
			$VALORVENCIMENTOANTECIP = $o->VALORVENCIMENTOANTECIP;
			$VALORNOTACREDITO = $o->VALORNOTACREDITO;
			$VALORADIANTAMENTO = $o->VALORADIANTAMENTO;
			$VALORDEVOLUCAO = $o->VALORDEVOLUCAO;
			$JUROSDIA = $o->JUROSDIA;
			$CAPMENSAL = $o->CAPMENSAL;
			$DESCONTOCOMERCIAL = $o->DESCONTOCOMERCIAL;
			$TAXASVENDOR = $o->TAXASVENDOR;
			$JUROSVENDOR = $o->JUROSVENDOR;
			$CODCOLCFO = $o->CODCOLCFO;
			$CODCFO = $o->CODCFO;
			$CODCOLCXA = $o->CODCOLCXA;
			$CODCXA = $o->CODCXA;
			$CODTDO = $o->CODTDO;
			$CODFILIAL = $o->CODFILIAL;
			$CODDEPARTAMENTO = $o->CODDEPARTAMENTO;
			$NUMEROCHEQUE = $o->NUMEROCHEQUE;
			//$SERIEDOCUMENTO = $o->SERIEDOCUMENTO;
			$SERIEDOCUMENTO = mt_rand();
			$IDADIANTAMENTO = $o->IDADIANTAMENTO;
			$IDNOTACREDITO = $o->IDNOTACREDITO;
			$IDLANREPASSE = $o->IDLANREPASSE;
			$IDDEVOLUCAO = $o->IDDEVOLUCAO;
			$IDBAIXAPARCIAL = $o->IDBAIXAPARCIAL;
			$IDIRRF = $o->IDIRRF;
			$IDCNT = $o->IDCNT;
			$CODTB1FLX = $o->CODTB1FLX;
			$CODTB2FLX = $o->CODTB2FLX;
			$CODTB3FLX = $o->CODTB3FLX;
			$CODTB4FLX = $o->CODTB4FLX;
			$CODTB5FLX = $o->CODTB5FLX;
			$TIPOCONTABILLAN = $o->TIPOCONTABILLAN;
			$CODMOEVALORORIGINAL = $o->CODMOEVALORORIGINAL;
			$CODINDEXADOR = $o->CODINDEXADOR;
			$FILIALCONTABIL = $o->FILIALCONTABIL;
			$NUMEROCONTABIL = $o->NUMEROCONTABIL;
			$SEGUNDONUMERO = $o->SEGUNDONUMERO;
			$LIBAUTORIZADA = $o->LIBAUTORIZADA;
			$STATUSEXPORTACAO = $o->STATUSEXPORTACAO;
			$NUMLOTECONTABIL = $o->NUMLOTECONTABIL;
			$STATUSEXTRATO = $o->STATUSEXTRATO;
			$CAMPOALFAOP1 = $o->CAMPOALFAOP1;
			$CAMPOALFAOP2 = $o->CAMPOALFAOP2;
			$CAMPOALFAOP3 = $o->CAMPOALFAOP3;
			$CANCELADOFAT = $o->CANCELADOFAT;
			$FATURADOFAT = $o->FATURADOFAT;
			$CNABCARTEIRA = $o->CNABCARTEIRA;
			$CNABCOMANDO = $o->CNABCOMANDO;
			$CNABACEITE = $o->CNABACEITE;
			$CNABINSTRUCAOCOD1 = $o->CNABINSTRUCAOCOD1;
			$CNABINSTRUCAOCOD2 = $o->CNABINSTRUCAOCOD2;
			$CNABSTATUS = $o->CNABSTATUS;
			$CNABBANCO = $o->CNABBANCO;
			$REEMBOLSAVEL = $o->REEMBOLSAVEL;
			$CODVEN = $o->CODVEN;
			$TIPOSAC = $o->TIPOSAC;
			$PERLETIVO = $o->PERLETIVO;
			$PARCELA = $o->PARCELA;
			$COTA = $o->COTA;
			$CODBAIXA = $o->CODBAIXA;
			$MENSBAIXA = $o->MENSBAIXA;
			$LOCPAG = $o->LOCPAG;
			$LOTE = $o->LOTE;
			$NUMRECIBO = $o->NUMRECIBO;
			$VRDEP = $o->VRDEP;
			$SERVEXTRA = $o->SERVEXTRA;
			$DTALT = $o->DTALT;
			$HRALT = $o->HRALT;
			$USUARIO = $o->USUARIO;
			$CODRPR = $o->CODRPR;
			$BAIXAAUTORIZADA = $o->BAIXAAUTORIZADA;
			$TEMCHEQUEPARCIAL = $o->TEMCHEQUEPARCIAL;
			$JAIMPRIMIU = $o->JAIMPRIMIU;
			$EMITIDO = $o->EMITIDO;
			$NUMBLOQUEIOS = $o->NUMBLOQUEIOS;
			$CODUSUDESBLOQUEIO1 = $o->CODUSUDESBLOQUEIO1;
			$CODUSUDESBLOQUEIO2 = $o->CODUSUDESBLOQUEIO2;
			$NUMCONTABILBX = $o->NUMCONTABILBX;
			$CODEVENTO = $o->CODEVENTO;
			$CODEVENTOBAIXA = $o->CODEVENTOBAIXA;
			$CHAPA = $o->CHAPA;
			$COTACAOINCLUSAO = $o->COTACAOINCLUSAO;
			$COTACAOBAIXA = $o->COTACAOBAIXA;
			$CARENCIAJUROS = $o->CARENCIAJUROS;
			$TIPOJUROSDIA = $o->TIPOJUROSDIA;
			$USUARIOCRIACAO = $o->USUARIOCRIACAO;
			$DATAALTERACAO = $o->DATAALTERACAO;
			$ALTERACAOBLOQUEADA = $o->ALTERACAOBLOQUEADA;
			$MULTADIA = $o->MULTADIA;
			$IDFORMAPAGTO = $o->IDFORMAPAGTO;
			$VALOROPERACAODESCONTO = $o->VALOROPERACAODESCONTO;
			$DESCONTADO = $o->DESCONTADO;
			$VALORINSS = $o->VALORINSS;
			$VALORDEDUCAO = $o->VALORDEDUCAO;
			$NUMLOTECONTABILBX = $o->NUMLOTECONTABILBX;
			$CNABAUTENTICACAO = $o->CNABAUTENTICACAO;
			$CODDIARIO = $o->CODDIARIO;
			$SEQDIARIO = $o->SEQDIARIO;
			$APLICFORMULA = $o->APLICFORMULA;
			$FORMULAJUROS = $o->FORMULAJUROS;
			$FORMULADESCONTO = $o->FORMULADESCONTO;
			$FORMULAMULTA = $o->FORMULAMULTA;
			$FORMULACAPITALIZACAO = $o->FORMULACAPITALIZACAO;
			$FORMULAVALOROP1 = $o->FORMULAVALOROP1;
			$FORMULAVALOROP2 = $o->FORMULAVALOROP2;
			$FORMULAVALOROP3 = $o->FORMULAVALOROP3;
			$FORMULAVALOROP4 = $o->FORMULAVALOROP4;
			$FORMULAVALOROP5 = $o->FORMULAVALOROP5;
			$FORMULAVALOROP6 = $o->FORMULAVALOROP6;
			$FORMULAVALOROP7 = $o->FORMULAVALOROP7;
			$FORMULAVALOROP8 = $o->FORMULAVALOROP8;
			$INSSEMOUTRAEMPRESA = $o->INSSEMOUTRAEMPRESA;
			$PERCENTBASEINSS = $o->PERCENTBASEINSS;
			$OCAUTONOMO = $o->OCAUTONOMO;
			$CODDIARIOBAIXA = $o->CODDIARIOBAIXA;
			$SEQDIARIOBAIXA = $o->SEQDIARIOBAIXA;
			$SEQDIARIOESTORNOBAIXA = $o->SEQDIARIOESTORNOBAIXA;
			$SEQDIARIOESTORNO = $o->SEQDIARIOESTORNO;
			$NSEQITMCNT = $o->NSEQITMCNT;
			$DATAFATCNT = $o->DATAFATCNT;
			$NUMSEQRECIBO = $o->NUMSEQRECIBO;
			$DATARECIBO = $o->DATARECIBO;
			$CODRECEITA = $o->CODRECEITA;
			$ALIQUOTA = $o->ALIQUOTA;
			$IDGUIA = $o->IDGUIA;
			$PERCBASEINSSEMPREGADO = $o->PERCBASEINSSEMPREGADO;
			$IMPOSTOEDITADO = $o->IMPOSTOEDITADO;
			$REUTILIZACAO = $o->REUTILIZACAO;
			$CNABCODRETORNO = $o->CNABCODRETORNO;
			$MOEDAVINCULO = $o->MOEDAVINCULO;
			$IDBOLETO = $o->IDBOLETO;
			$CATEGORIAAUTONOMO = $o->CATEGORIAAUTONOMO;
			$VALORSESTSENAT = $o->VALORSESTSENAT;
			$CONVENIO = $o->CONVENIO;
			$DIGCONVENIO = $o->DIGCONVENIO;
			$CODCOLCFOORIGEM = $o->CODCOLCFOORIGEM;
			$CODCFOORIGEM = $o->CODCFOORIGEM;
			$VRPERDAFINANCEIRA = $o->VRPERDAFINANCEIRA;
			$VRBASEINSSOUTRAEMPRESA = $o->VRBASEINSSOUTRAEMPRESA;
			$NSEQITMPREVISAO = $o->NSEQITMPREVISAO;
			$VALORSERVICO = $o->VALORSERVICO;
			$VRBASEINSS = $o->VRBASEINSS;
			$VRBASEIRRF = $o->VRBASEIRRF;
			$STATUSDDA = $o->STATUSDDA;
			$VALORDEDUCAODEPENDENTES = $o->VALORDEDUCAODEPENDENTES;
			$BAIXAPENDENTE = $o->BAIXAPENDENTE;
			$MULTAFIXA = $o->MULTAFIXA;
			$STATUSAVP = $o->STATUSAVP;
			$IDBORDERO = $o->IDBORDERO;
			$RECCREATEDBY = $o->RECCREATEDBY;
			$RECCREATEDON = $o->RECCREATEDON;
			$RECMODIFIEDBY = $o->RECMODIFIEDBY;
			$RECMODIFIEDON = $o->RECMODIFIEDON;
			$VALORORIGINALBX = $o->VALORORIGINALBX;
			$VALORDESCONTOBX = $o->VALORDESCONTOBX;
			$VALORJUROSBX = $o->VALORJUROSBX;
			$VALORMULTABX = $o->VALORMULTABX;
			$VALORCAPBX = $o->VALORCAPBX;
			$VALOROP1BX = $o->VALOROP1BX;
			$VALOROP2BX = $o->VALOROP2BX;
			$VALOROP3BX = $o->VALOROP3BX;
			$VALOROP4BX = $o->VALOROP4BX;
			$VALOROP5BX = $o->VALOROP5BX;
			$VALOROP6BX = $o->VALOROP6BX;
			$VALOROP7BX = $o->VALOROP7BX;
			$VALOROP8BX = $o->VALOROP8BX;
			$VALORINSSBX = $o->VALORINSSBX;
			$VALORIRRFBX = $o->VALORIRRFBX;
			$VALORSESTSENATBX = $o->VALORSESTSENATBX;
			$VALORDEVOLUCAOBX = $o->VALORDEVOLUCAOBX;
			$VALORNOTACREDITOBX = $o->VALORNOTACREDITOBX;
			$VALORADIANTAMENTOBX = $o->VALORADIANTAMENTOBX;
			$VALORJUROSVENDORBX = $o->VALORJUROSVENDORBX;
			$VALORRETENCOESBX = $o->VALORRETENCOESBX;
			$VALORPERDAFINANCEIRABX = $o->VALORPERDAFINANCEIRABX;
			$VALORVINCULADO = $o->VALORVINCULADO;
			$MODELOCONTABILIZACAO = $o->MODELOCONTABILIZACAO;
			$MODELOCONTABILIZACAOBAIXA = $o->MODELOCONTABILIZACAOBAIXA;
			$IDOPERACAOBAIXA = $o->IDOPERACAOBAIXA;
			$VALORDESCONTODUPLICATA = $o->VALORDESCONTODUPLICATA;
			$IDLANMOVORIGEM = $o->IDLANMOVORIGEM;
			$VALORDESCONTOACORDO = $o->VALORDESCONTOACORDO;
			$VALORJUROSACORDO = $o->VALORJUROSACORDO;
			$VALORACRESCIMOACORDO = $o->VALORACRESCIMOACORDO;
			$NUMEROPARCELAS = $o->NUMEROPARCELAS;
			$BANDEIRA = (! empty ( $o->BANDEIRA )) ? $o->BANDEIRA : '';
			$TIPOPAGAMENTO = $o->TIPOPAGAMENTO;
			$IDORDEM = $o->IDORDEM;
			
			$dias = 0;
			
			if ($TIPOPAGAMENTO == 'credito' or $TIPOPAGAMENTO == 'debito') {
				
				if (! empty ( $BANDEIRA )) {
					$CODCFO = $vetMapearBandeiraCartaoCliente [$BANDEIRA];
					$CODCXA = $vetMapearBandeiraCartaoContaCaixa [$BANDEIRA];
					
					if ($TIPOPAGAMENTO == 'credito') {
						$dias = '30';
					} else {
						$dias = '1';
					}
				} else {
					$CODCXA = '';
				}
			
			} else {
				$CODCXA = 'CX';
			}
			
			if ($TIPOPAGAMENTO == 'carteira') {
				$dias = 5;
			} elseif ($TIPOPAGAMENTO == 'nota') {
				$dias = 30;
			}
			
			if (! empty ( $CODCFO ) && ! empty ( $CODCXA ) && ! empty ( $CODVEN ) && ! empty ( $CODTB1FLX ) && ! empty ( $CODTB2FLX )) {
				
				$NUMEROPARCELAS = (! empty ( $NUMEROPARCELAS ) && $NUMEROPARCELAS > 0 && $TIPOPAGAMENTO == 'credito') ? $NUMEROPARCELAS : 1;
				$DATAEMISSAO = date ( 'Y-m-d', strtotime ( $DATAEMISSAO ) );
				$NUMERODOCUMENTOORIGINAL = $NUMERODOCUMENTO;
				//$SERIEDOCUMENTOORIGINAL = $SERIEDOCUMENTO;
				$HISTORICO = (! empty ( $HISTORICO )) ? $HISTORICO : "ORDEM No: " . $SEGUNDONUMERO;
				
				for($i = 1; $i <= $NUMEROPARCELAS; $i ++) {
					
					if ($TIPOPAGAMENTO == 'credito') {
						$NUMERODOCUMENTO = "$NUMERODOCUMENTO" . "-" . $i;
					}
					
					if ($TIPOPAGAMENTO == 'debito' && empty ( $NUMERODOCUMENTO )) {
						list ( $ano, $mes, $dia ) = explode ( '-', date ( 'y-m-d', strtotime ( $DATAEMISSAO ) ) );
						$NUMERODOCUMENTO = "$dia" . "$mes" . "$ano";
					}
					
					//$SERIEDOCUMENTO = $SERIEDOCUMENTO . "$i";
					
					$DATAVENCIMENTO = date ( 'Y-m-d', strtotime ( "+$dias days", strtotime ( $DATAEMISSAO ) ) );
					list ( $ano, $mes, $dia ) = explode ( '-', $DATAVENCIMENTO );
					$data = mktime ( 0, 0, 0, $mes, $dia, $ano );
					
					if (in_array ( $data, Util::dias_feriados ( date ( 'Y', strtotime ( $DATAVENCIMENTO ) ) ) )) {
						$DATAVENCIMENTO = date ( 'Y-m-d', strtotime ( "+1 days", strtotime ( $DATAVENCIMENTO ) ) );
						
						if (date ( 'w', strtotime ( $DATAVENCIMENTO ) ) == 6) {
							$DATAVENCIMENTO = date ( 'Y-m-d', strtotime ( "+2 days", strtotime ( $DATAVENCIMENTO ) ) );
						} elseif (date ( 'w', strtotime ( $DATAVENCIMENTO ) ) == 0) {
							$DATAVENCIMENTO = date ( 'Y-m-d', strtotime ( "+1 days", strtotime ( $DATAVENCIMENTO ) ) );
						}
					
					} elseif (date ( 'w', strtotime ( $DATAVENCIMENTO ) ) == 6) {
						$DATAVENCIMENTO = date ( 'Y-m-d', strtotime ( "+2 days", strtotime ( $DATAVENCIMENTO ) ) );
					} elseif (date ( 'w', strtotime ( $DATAVENCIMENTO ) ) == 0) {
						$DATAVENCIMENTO = date ( 'Y-m-d', strtotime ( "+1 days", strtotime ( $DATAVENCIMENTO ) ) );
					}
					
					$DATAPREVBAIXA = $DATAVENCIMENTO;
					
					$sql = "
		
		SET ANSI_WARNINGS OFF;
		SET DATEFORMAT ymd;
		
		INSERT INTO FLAN (
			CODCOLIGADA, 
			IDLAN, 
			NUMERODOCUMENTO, 
			CODIGOBARRA, 
			IPTE, 
			CNABNOSSONUMERO, 
			NFOUDUP, 
			CLASSIFICACAO, 
			PAGREC, 
			STATUSLAN, 
			CODAPLICACAO, 
			CODCOLXCX, 
			IDXCX, 
			IDFAT, 
			IDMOV, 
			IDSESSAO, 
			IDPGTO, 
			CODCCUSTO, 
			HISTORICO, 
			DATACRIACAO, 
			DATAVENCIMENTO, 
			DATAEMISSAO, 
			DATABAIXA, 
			DATAPREVBAIXA, 
			DATACONTABILIZ, 
			DATACANCELAMENTO, 
			DATACANCELBAIXA, 
			DATAESTORNOLAN, 
			DATACHEQUE, 
			DATACONTABILIZBX, 
			DATAVENCIMENTOANTECIP, 
			DATAOP1, 
			DATAOP2, 
			DATAOP3, 
			DATAOP4, 
			DATAOP5, 
			DATAPAG, 
			MESDECOMPETENCIA, 
			VALORORIGINAL, 
			VALORBAIXADO, 
			VALORCAP, 
			VALORJUROS, 
			VALORDESCONTO, 
			VALORCHEQUE, 
			VALOROP1, 
			VALOROP2, 
			VALOROP3, 
			VALOROP4, 
			VALOROP5, 
			VALOROP6, 
			VALOROP7, 
			VALOROP8, 
			VALORMULTA, 
			VALORAUXILIAR, 
			VALORBASEIRRF, 
			VALORIRRF, 
			VALORREPASSE, 
			VALORVENCIMENTOANTECIP, 
			VALORNOTACREDITO, 
			VALORADIANTAMENTO, 
			VALORDEVOLUCAO, 
			JUROSDIA, 
			CAPMENSAL, 
			DESCONTOCOMERCIAL, 
			TAXASVENDOR, 
			JUROSVENDOR, 
			CODCOLCFO, 
			CODCFO, 
			CODCOLCXA, 
			CODCXA, 
			CODTDO, 
			CODFILIAL, 
			CODDEPARTAMENTO, 
			NUMEROCHEQUE, 
			SERIEDOCUMENTO, 
			IDADIANTAMENTO, 
			IDNOTACREDITO, 
			IDLANREPASSE, 
			IDDEVOLUCAO, 
			IDBAIXAPARCIAL, 
			IDIRRF, 
			IDCNT, 
			CODTB1FLX, 
			CODTB2FLX, 
			CODTB3FLX, 
			CODTB4FLX, 
			CODTB5FLX, 
			TIPOCONTABILLAN, 
			CODMOEVALORORIGINAL, 
			CODINDEXADOR, 
			FILIALCONTABIL, 
			NUMEROCONTABIL, 
			SEGUNDONUMERO, 
			LIBAUTORIZADA, 
			STATUSEXPORTACAO, 
			NUMLOTECONTABIL, 
			STATUSEXTRATO, 
			CAMPOALFAOP1, 
			CAMPOALFAOP2, 
			CAMPOALFAOP3, 
			CANCELADOFAT, 
			FATURADOFAT, 
			CNABCARTEIRA, 
			CNABCOMANDO, 
			CNABACEITE, 
			CNABINSTRUCAOCOD1, 
			CNABINSTRUCAOCOD2, 
			CNABSTATUS, 
			CNABBANCO, 
			REEMBOLSAVEL, 
			CODVEN, 
			TIPOSAC, 
			PERLETIVO, 
			PARCELA, 
			COTA, 
			CODBAIXA, 
			MENSBAIXA, 
			LOCPAG, 
			LOTE, 
			NUMRECIBO, 
			VRDEP, 
			SERVEXTRA, 
			DTALT, 
			HRALT, 
			USUARIO, 
			CODRPR, 
			BAIXAAUTORIZADA, 
			TEMCHEQUEPARCIAL, 
			JAIMPRIMIU, 
			EMITIDO, 
			NUMBLOQUEIOS, 
			CODUSUDESBLOQUEIO1, 
			CODUSUDESBLOQUEIO2, 
			NUMCONTABILBX, 
			CODEVENTO, 
			CODEVENTOBAIXA, 
			CHAPA, 
			COTACAOINCLUSAO, 
			COTACAOBAIXA, 
			CARENCIAJUROS, 
			TIPOJUROSDIA, 
			USUARIOCRIACAO, 
			DATAALTERACAO, 
			ALTERACAOBLOQUEADA, 
			MULTADIA, 
			IDFORMAPAGTO, 
			VALOROPERACAODESCONTO, 
			DESCONTADO, 
			VALORINSS, 
			VALORDEDUCAO, 
			NUMLOTECONTABILBX, 
			CNABAUTENTICACAO, 
			CODDIARIO, 
			SEQDIARIO, 
			APLICFORMULA, 
			FORMULAJUROS, 
			FORMULADESCONTO, 
			FORMULAMULTA, 
			FORMULACAPITALIZACAO, 
			FORMULAVALOROP1, 
			FORMULAVALOROP2, 
			FORMULAVALOROP3, 
			FORMULAVALOROP4, 
			FORMULAVALOROP5, 
			FORMULAVALOROP6, 
			FORMULAVALOROP7, 
			FORMULAVALOROP8, 
			INSSEMOUTRAEMPRESA, 
			PERCENTBASEINSS, 
			OCAUTONOMO, 
			CODDIARIOBAIXA, 
			SEQDIARIOBAIXA, 
			SEQDIARIOESTORNOBAIXA, 
			SEQDIARIOESTORNO, 
			NSEQITMCNT, 
			DATAFATCNT, 
			NUMSEQRECIBO, 
			DATARECIBO, 
			CODRECEITA, 
			ALIQUOTA, 
			IDGUIA, 
			PERCBASEINSSEMPREGADO, 
			IMPOSTOEDITADO, 
			REUTILIZACAO, 
			CNABCODRETORNO, 
			MOEDAVINCULO, 
			IDBOLETO, 
			CATEGORIAAUTONOMO, 
			VALORSESTSENAT, 
			CONVENIO, 
			DIGCONVENIO, 
			CODCOLCFOORIGEM, 
			CODCFOORIGEM, 
			VRPERDAFINANCEIRA, 
			VRBASEINSSOUTRAEMPRESA, 
			NSEQITMPREVISAO, 
			VALORSERVICO, 
			VRBASEINSS, 
			VRBASEIRRF, 
			STATUSDDA, 
			VALORDEDUCAODEPENDENTES, 
			BAIXAPENDENTE, 
			MULTAFIXA, 
			STATUSAVP, 
			IDBORDERO, 
			RECCREATEDBY, 
			RECCREATEDON, 
			RECMODIFIEDBY, 
			RECMODIFIEDON, 
			VALORORIGINALBX, 
			VALORDESCONTOBX, 
			VALORJUROSBX, 
			VALORMULTABX, 
			VALORCAPBX, 
			VALOROP1BX, 
			VALOROP2BX, 
			VALOROP3BX, 
			VALOROP4BX, 
			VALOROP5BX, 
			VALOROP6BX, 
			VALOROP7BX, 
			VALOROP8BX, 
			VALORINSSBX, 
			VALORIRRFBX, 
			VALORSESTSENATBX, 
			VALORDEVOLUCAOBX, 
			VALORNOTACREDITOBX, 
			VALORADIANTAMENTOBX, 
			VALORJUROSVENDORBX, 
			VALORRETENCOESBX, 
			VALORPERDAFINANCEIRABX, 
			VALORVINCULADO, 
			MODELOCONTABILIZACAO, 
			MODELOCONTABILIZACAOBAIXA, 
			IDOPERACAOBAIXA, 
			VALORDESCONTODUPLICATA, 
			IDLANMOVORIGEM, 
			VALORDESCONTOACORDO, 
			VALORJUROSACORDO, 
			VALORACRESCIMOACORDO
	)
	VALUES (
		'$CODCOLIGADA', 
		'$IDLAN', 
		'$NUMERODOCUMENTO', 
		NULL, 
		NULL, 
		NULL, 
		0, 
		0, 
		1, 
		0, 
		'F', 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		'$HISTORICO', 
		'$DATACRIACAO', 
		'$DATAVENCIMENTO', 
		'$DATAEMISSAO', 
		NULL, 
		'$DATAPREVBAIXA', 
		'$DATACONTABILIZ', 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		$VALORORIGINAL, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		1, 
		$VALORBASEIRRF, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		NULL, 
		0, 
		0, 
		1, 
		'$CODCFO', 
		0, 
		'$CODCXA', 
		'$CODTDO', 
		1, 
		NULL, 
		NULL, 
		'$SERIEDOCUMENTO', 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		'$CODTB1FLX', 
		'$CODTB2FLX',
		NULL, 
		NULL, 
		NULL, 
		$TIPOCONTABILLAN, 
		'R$', 
		NULL, 
		NULL, 
		'$NUMEROCONTABIL', 
		'$SEGUNDONUMERO',
		0, 
		0, 
		60, 
		0, 
		NULL, 
		NULL, 
		'$CAMPOALFAOP3', 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		0, 
		NULL, 
		NULL, 
		0, 
		NULL, 
		0, 
		'$CODVEN', 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		'mestre', 
		NULL, 
		1, 
		0, 
		0, 
		NULL, 
		0, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		0, 
		0, 
		0, 
		0, 
		'mestre', 
		'$DATAALTERACAO', 
		0, 
		0, 
		NULL, 
		NULL, 
		0, 
		0, 
		0, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		'F', 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		0, 
		$PERCENTBASEINSS, 
		0, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		$PERCBASEINSSEMPREGADO, 
		0, 
		0, 
		NULL, 
		NULL, 
		NULL, 
		0, 
		0, 
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		0, 
		0, 
		NULL, 
		$VALORSERVICO, 
		0, 
		0, 
		0, 
		0, 
		0, 
		NULL, 
		0, 
		NULL, 
		'mestre', 
		getdate(), 
		'mestre', 
		getdate(), 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		0, 
		NULL, 
		0, 
		NULL, 
		0, 
		0, 
		0
	);

	UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDLAN) FROM FLAN WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDLAN' AND CODCOLIGADA = 1;	
		";
					
					if ($TIPOPAGAMENTO == 'credito' or $TIPOPAGAMENTO == 'debito') {
						$sql .= "
			INSERT INTO CLANCAMENTO (CODCOLIGADA, CODLOTE, IDLANCAMENTO, DESCRICAO, CODUSUARIO, TIPOBLOQ, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			VALUES (1, 60, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO)) + (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO))), 'Descricao do Lancamento Contabil', NULL, NULL, 'mestre', getdate(), 'mestre', getdate());

			INSERT INTO COPERACAO (CODCOLIGADA, IDOPERACAO, ORIGEM, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, LIBERADO)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1)) + (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1))), 'FLAN', 'mestre', GETDATE(), 'mestre', GETDATE(), NULL);
			
			INSERT INTO CPARTIDA (CODCOLIGADA, IDPARTIDA, CODLOTE, IDLANCAMENTO, LCTREF, CODLOTEORIGEM, CODFILIAL, CODDEPARTAMENTO, CODCCUSTO, DOCUMENTO, DATA, CODCOLDEBITO, DEBITO, CODCOLCREDITO, CREDITO, CODCOLPARTIDA, PARTIDA, VALOR, VALOR2, DATA2, CODHISTP, COMPLEMENTO, IDPARTICIPANTE, USUARIO, DATAINCLU, USUARIOALTER, DATAALTER, USUARIOINTEGRACAO, DATAINTEGRACAO, DATALIBERACAO, CODDIARIO, SEQDIARIO, INTEGRAAPLICACAO, INTEGRACHAVE, TIPOAGRUP, RATEIO, ORIGINADONOVOMOD, TIPOGERACAO, LCTREFORIGEM, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDPARTIDA) FROM CPARTIDA)) + (SELECT MAX(IDPARTIDA) FROM CPARTIDA))), 60, (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO), (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(LCTREF) FROM CPARTIDA)) + (SELECT MAX(LCTREF) FROM CPARTIDA))), NULL, 1, NULL, NULL, (SELECT NUMERODOCUMENTO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), (SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 1, (SELECT CODCONTA FROM FCXACONT WHERE CODCOLIGADA = 1 AND CODCXA = (SELECT CODCXA FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN) AND TIPO = 1), 0, NULL, 0, NULL, (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 0, (SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), '99', (SELECT HISTORICO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), NULL, 'mestre', GETDATE(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', (SELECT 'I' + CAST($IDLAN AS VARCHAR)), NULL, NULL, 1, 'O', NULL, 'mestre', GETDATE(), 'mestre', GETDATE());
			
			INSERT INTO CCONT (CODCOLIGADA, IDCONT, IDOPERACAO, IDPARTIDA, VALOR, STATUS, TIPO, VALOR2, IDESTORNOCONT, IDGRUPOCONT, VERSAOANTERIOR, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, DOCUMENTO_AGP, COMPLEMENTO_AGP)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1)) + (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1))), (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1), (SELECT MAX(IDPARTIDA) FROM CPARTIDA), (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 'C', 1, 0, NULL, NULL, NULL, 'mestre', GETDATE(), 'mestre', GETDATE(), NULL, NULL);
			
			INSERT INTO CPARTIDA (CODCOLIGADA, IDPARTIDA, CODLOTE, IDLANCAMENTO, LCTREF, CODLOTEORIGEM, CODFILIAL, CODDEPARTAMENTO, CODCCUSTO, DOCUMENTO, DATA, CODCOLDEBITO, DEBITO, CODCOLCREDITO, CREDITO, CODCOLPARTIDA, PARTIDA, VALOR, VALOR2, DATA2, CODHISTP, COMPLEMENTO, IDPARTICIPANTE, USUARIO, DATAINCLU, USUARIOALTER, DATAALTER, USUARIOINTEGRACAO, DATAINTEGRACAO, DATALIBERACAO, CODDIARIO, SEQDIARIO, INTEGRAAPLICACAO, INTEGRACHAVE, TIPOAGRUP, RATEIO, ORIGINADONOVOMOD, TIPOGERACAO, LCTREFORIGEM, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDPARTIDA) FROM CPARTIDA)) + (SELECT MAX(IDPARTIDA) FROM CPARTIDA))), 60, (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO), (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(LCTREF) FROM CPARTIDA)) + (SELECT MAX(LCTREF) FROM CPARTIDA))), NULL, 1, NULL, NULL, (SELECT NUMERODOCUMENTO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN),(SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 0, NULL, 1, (SELECT CODCONTA FROM FTB1CONT WHERE CODCOLIGADA = 1 AND CODTB1FLX = (SELECT CODTB1FLX FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN) AND DEBOUCRED = 2), 0, NULL, (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 0, (SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), '99', (SELECT HISTORICO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), NULL, 'mestre', GETDATE(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', (SELECT 'I' + CAST($IDLAN AS VARCHAR)), NULL, NULL, 1, 'O', NULL, 'mestre', GETDATE(), 'mestre', GETDATE());
			
			INSERT INTO CCONT (CODCOLIGADA, IDCONT, IDOPERACAO, IDPARTIDA, VALOR, STATUS, TIPO, VALOR2, IDESTORNOCONT, IDGRUPOCONT, VERSAOANTERIOR, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, DOCUMENTO_AGP, COMPLEMENTO_AGP)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1)) + (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1))), (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1), (SELECT MAX(IDPARTIDA) FROM CPARTIDA), (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 'C', 2, 0, NULL, NULL, NULL, 'mestre', GETDATE(), 'mestre', GETDATE(), NULL, NULL);
			
			UPDATE FLAN SET IDOPERACAO = (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1) WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN;
			
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDLANCAMENTO' AND CODCOLIGADA = 1; 
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDOPERACAO' AND CODCOLIGADA = 1;
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDPARTIDA) FROM CPARTIDA WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDPARTIDA' AND CODCOLIGADA = 1; 
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDCONT' AND CODCOLIGADA = 1;
			";
					} else {
						$sql .= "
			INSERT INTO CLANCAMENTO (CODCOLIGADA, CODLOTE, IDLANCAMENTO, DESCRICAO, CODUSUARIO, TIPOBLOQ, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			VALUES (1, 60, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO)) + (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO))), 'Descricao do Lancamento Contabil', NULL, NULL, 'mestre', getdate(), 'mestre', getdate());

			INSERT INTO COPERACAO (CODCOLIGADA, IDOPERACAO, ORIGEM, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, LIBERADO)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1)) + (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1))), 'FLAN', 'mestre', GETDATE(), 'mestre', GETDATE(), NULL);
			
			INSERT INTO CPARTIDA (CODCOLIGADA, IDPARTIDA, CODLOTE, IDLANCAMENTO, LCTREF, CODLOTEORIGEM, CODFILIAL, CODDEPARTAMENTO, CODCCUSTO, DOCUMENTO, DATA, CODCOLDEBITO, DEBITO, CODCOLCREDITO, CREDITO, CODCOLPARTIDA, PARTIDA, VALOR, VALOR2, DATA2, CODHISTP, COMPLEMENTO, IDPARTICIPANTE, USUARIO, DATAINCLU, USUARIOALTER, DATAALTER, USUARIOINTEGRACAO, DATAINTEGRACAO, DATALIBERACAO, CODDIARIO, SEQDIARIO, INTEGRAAPLICACAO, INTEGRACHAVE, TIPOAGRUP, RATEIO, ORIGINADONOVOMOD, TIPOGERACAO, LCTREFORIGEM, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDPARTIDA) FROM CPARTIDA)) + (SELECT MAX(IDPARTIDA) FROM CPARTIDA))), 60, (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO), (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(LCTREF) FROM CPARTIDA)) + (SELECT MAX(LCTREF) FROM CPARTIDA))), NULL, 1, NULL, NULL, (SELECT NUMERODOCUMENTO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), (SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 1, '1.1.04.001.1123', 0, NULL, 0, NULL, (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 0, (SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), '99', (SELECT HISTORICO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), NULL, 'mestre', GETDATE(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', (SELECT 'I' + CAST($IDLAN AS VARCHAR)), NULL, NULL, 1, 'O', NULL, 'mestre', GETDATE(), 'mestre', GETDATE());
			
			INSERT INTO CCONT (CODCOLIGADA, IDCONT, IDOPERACAO, IDPARTIDA, VALOR, STATUS, TIPO, VALOR2, IDESTORNOCONT, IDGRUPOCONT, VERSAOANTERIOR, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, DOCUMENTO_AGP, COMPLEMENTO_AGP)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1)) + (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1))), (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1), (SELECT MAX(IDPARTIDA) FROM CPARTIDA), (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 'C', 1, 0, NULL, NULL, NULL, 'mestre', GETDATE(), 'mestre', GETDATE(), NULL, NULL);
			
			INSERT INTO CPARTIDA (CODCOLIGADA, IDPARTIDA, CODLOTE, IDLANCAMENTO, LCTREF, CODLOTEORIGEM, CODFILIAL, CODDEPARTAMENTO, CODCCUSTO, DOCUMENTO, DATA, CODCOLDEBITO, DEBITO, CODCOLCREDITO, CREDITO, CODCOLPARTIDA, PARTIDA, VALOR, VALOR2, DATA2, CODHISTP, COMPLEMENTO, IDPARTICIPANTE, USUARIO, DATAINCLU, USUARIOALTER, DATAALTER, USUARIOINTEGRACAO, DATAINTEGRACAO, DATALIBERACAO, CODDIARIO, SEQDIARIO, INTEGRAAPLICACAO, INTEGRACHAVE, TIPOAGRUP, RATEIO, ORIGINADONOVOMOD, TIPOGERACAO, LCTREFORIGEM, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDPARTIDA) FROM CPARTIDA)) + (SELECT MAX(IDPARTIDA) FROM CPARTIDA))), 60, (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO), (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(LCTREF) FROM CPARTIDA)) + (SELECT MAX(LCTREF) FROM CPARTIDA))), NULL, 1, NULL, NULL, (SELECT NUMERODOCUMENTO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN),(SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 0, NULL, 1, '3.1.01.001.0001.00001', 0, NULL, (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 0, (SELECT DATAEMISSAO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), '99', (SELECT HISTORICO FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), NULL, 'mestre', GETDATE(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', (SELECT 'I' + CAST($IDLAN AS VARCHAR)), NULL, NULL, 1, 'O', NULL, 'mestre', GETDATE(), 'mestre', GETDATE());
			
			INSERT INTO CCONT (CODCOLIGADA, IDCONT, IDOPERACAO, IDPARTIDA, VALOR, STATUS, TIPO, VALOR2, IDESTORNOCONT, IDGRUPOCONT, VERSAOANTERIOR, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON, DOCUMENTO_AGP, COMPLEMENTO_AGP)
			VALUES (1, (SELECT (ROW_NUMBER() OVER (ORDER BY (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1)) + (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1))), (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1), (SELECT MAX(IDPARTIDA) FROM CPARTIDA), (SELECT VALORORIGINAL FROM FLAN WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN), 'C', 2, 0, NULL, NULL, NULL, 'mestre', GETDATE(), 'mestre', GETDATE(), NULL, NULL);
			
			UPDATE FLAN SET IDOPERACAO = (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1) WHERE CODCOLIGADA = 1 AND IDLAN = $IDLAN;
			
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDLANCAMENTO) FROM CLANCAMENTO WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDLANCAMENTO' AND CODCOLIGADA = 1; 
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDOPERACAO) FROM COPERACAO WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDOPERACAO' AND CODCOLIGADA = 1;
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDPARTIDA) FROM CPARTIDA WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDPARTIDA' AND CODCOLIGADA = 1; 
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDCONT) FROM CCONT WHERE CODCOLIGADA = 1) WHERE CODAUTOINC = 'IDCONT' AND CODCOLIGADA = 1;
			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(LCTREF) FROM CPARTIDA WHERE CODCOLIGADA = 1) WHERE CODCOLIGADA = 1 AND CODAUTOINC = 'LCTREF60';
			";
					}
					
					$sql .= "SET ANSI_WARNINGS OFF;";
					
					$db2->Execute ( $sql );
					
					$sql = "UPDATE AoAdOrder SET CustomPackNumber = 'integrado' WHERE Id = '$IDORDEM';";
					$db->Execute ( $sql );
					
					$NUMERODOCUMENTO = $NUMERODOCUMENTOORIGINAL;
					//$SERIEDOCUMENTO = $SERIEDOCUMENTOORIGINAL;
					
					if ($TIPOPAGAMENTO == 'credito') {
						$dias += 30;
					}
					
					$IDLAN ++;
				
				}
			}
		
		}
	}
}

?>